### ISSUE TITLE
Tomcat base image (tomcat:8.5-jre10) is deprecated

### ISSUE THREAD

**Issue by fenik** [castlemock/docker#3]
The current dockerfile references the tomcat:8.5-jre10 image, which - according to DockerHub - hasn't been updated for a year.

After a short research I've found the following related issue on the tomcat/docker-library project: https://github.com/docker-library/tomcat/issues/175

A possible solution would be to migrate to one of the JDK images available, e. g. 8.5-jdk11-openjdk. All available images can be found on the tomcat DockerHub page: https://hub.docker.com/_/tomcat

**Comment by karldahlgren** [comment]
Thank you for the suggestion @fenik.
I have done as you suggested and updated the Dockerfile to use JDK11 openJDK instead. It is part as the latest Docker image on Docker Hub.

Once again, thanks for reporting this.
Best regards,
Karl Dahlgren
