### ISSUE TITLE
Docker tag v1.61 try to download v1.62/castlemock.war not exist

### ISSUE THREAD

**Issue by ahmadabulaban** [castlemock/docker#9]
Hello

The tag v1.61 updated recently to use https://github.com/castlemock/castlemock/releases/download/v1.62/castlemock.war which currently not released yet.

I think it's better to keep tag v1.61 use matched release (v1.61) and create a new docker tag v1.62 for the new release of castlemock once it's released

**Comment by ahmadabulaban** [comment]
@karldahlgren

**Comment by karldahlgren** [comment]
Thank you for reporting this issue @ahmadabulaban!
This issue has now been resolved and docker tag v1.61 is now pointing towards Castle Mock v1.61.

Best regards,
Karl
